name: Build NV Travels APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Android Project Platform Files
        run: flutter create . --platforms=android
        working-directory: ./mobile_app

      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./mobile_app

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./mobile_app

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NV-Travels-App
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
          
